[package]
name = "yak"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[profile.dev]

[profile.release]

[dependencies]
spin = "0.9.8"
[dependencies.lazy_static]
version = "1.5.0"
features = ["spin_no_std"]

