[package]
name = "yak"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[profile.dev]

[profile.release]

[dependencies]
bit_field = "0.10.1"
spin = "0.9.8"
volatile = "0.4.4"
lazy_static = { version = "1.5.0", features = ["spin_no_std"] }

